---
title: "p8105_hw5_sc4636"
author: "Cui Sitong (sc4636)"
date: "11/7/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

* replacing missing values

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

function_na = function(x) {
  
  if (is.numeric(x)) {
    replace_na(
      x, mean(x, na.rm = TRUE)
    )
  } else if (is.character(x)) {
    replace_na(
      x, "virginica"
    )
  }
  
}

iris_na_replaced = map_df(iris_with_missing, function_na)
```

## Problem 2

```{r}

```

## Problem 3

```{r power analysis}

```










